# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 800)
        Form.setStyleSheet("QLineEdit{\n"
"border: none;\n"
"}\n"
"QPlainTextEdit{\n"
"border: none;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("QLabel{\n"
"font-weight: bold;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.treeView_xls = QtWidgets.QTreeView(Form)
        self.treeView_xls.setStyleSheet("QTreeView{\n"
"background-color:rgb(255, 236, 249)\n"
"}")
        self.treeView_xls.setObjectName("treeView_xls")
        self.verticalLayout.addWidget(self.treeView_xls)
        self.pushButton_xls_edit = QtWidgets.QPushButton(Form)
        self.pushButton_xls_edit.setObjectName("pushButton_xls_edit")
        self.verticalLayout.addWidget(self.pushButton_xls_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("QLabel{\n"
"font-weight: bold;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.treeView_database = QtWidgets.QTreeView(Form)
        self.treeView_database.setStyleSheet("QTreeView{\n"
"background-color:rgb(230, 245, 255)\n"
"}push")
        self.treeView_database.setObjectName("treeView_database")
        self.verticalLayout_2.addWidget(self.treeView_database)
        self.pushButton_database_add = QtWidgets.QPushButton(Form)
        self.pushButton_database_add.setObjectName("pushButton_database_add")
        self.verticalLayout_2.addWidget(self.pushButton_database_add)
        self.pushButton_database_delete = QtWidgets.QPushButton(Form)
        self.pushButton_database_delete.setObjectName("pushButton_database_delete")
        self.verticalLayout_2.addWidget(self.pushButton_database_delete)
        self.pushButton_database_edit = QtWidgets.QPushButton(Form)
        self.pushButton_database_edit.setObjectName("pushButton_database_edit")
        self.verticalLayout_2.addWidget(self.pushButton_database_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数据库生成脚本"))
        self.label_2.setText(_translate("Form", "保存路径"))
        self.pushButton_2.setText(_translate("Form", "选择数据保存路径"))
        self.label.setText(_translate("Form", "原始数据路径"))
        self.pushButton.setText(_translate("Form", "选择xls文件路径"))
        self.label_3.setText(_translate("Form", "*物料编码原表*"))
        self.pushButton_xls_edit.setText(_translate("Form", "编辑"))
        self.label_4.setText(_translate("Form", "*数据库导出表*"))
        self.pushButton_database_add.setText(_translate("Form", "新增"))
        self.pushButton_database_delete.setText(_translate("Form", "删除"))
        self.pushButton_database_edit.setText(_translate("Form", "编辑"))
        self.pushButton_3.setText(_translate("Form", "确定"))
